server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sharding_jdbc_sample?useSSL=false&&characterEncoding=UTF-8
    username: root
    password: root
  flyway:
    locations: classpath:/db/migration
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl:  org.apache.ibatis.logging.stdout.StdOutImpl


#logging:
#  level:
#    com:
#      watermelon:
#        sharding_jdbc_sample:
#          dao: debug
