server:
  port: 8082

spring:
  shardingsphere:
    datasource:
      names: ds0
      ds0:
        type: com.zaxxer.hikari.HikariDataSource #必填
        jdbc-url: jdbc:mysql://localhost:3306/sharding_jdbc_sample?useSSL=false&&characterEncoding=UTF-8 #必填
        username: root #必填
        password: root #必填
    sharding:
      tables:
        commodity:
          actual-data-nodes: ds0.commodity_$->{0..3} # sql查询时，会使用commodity_{0..3}的格式去查实际表
          table-strategy:
            inline:
              sharding-column: commodityId # 分片ID
              algorithm-expression: commodity_$->{(commodityId.hashCode() & Integer.MAX_VALUE) % 4} # 通过此表达式来计算具体的commodity表
    props:
      sql:
        show: false #可打印实际sql，分表后的实际表名

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
#    log-impl:  org.apache.ibatis.logging.stdout.StdOutImpl #sql日志，会把查询结果也打印出来


logging:
  level:
    com:
      watermelon:
        sharding_jdbc_sample:
          dao: debug